### ISSUE TITLE
Figure out how to check compatibility of method return types and type references in calling code

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/cloud-opensource-java#116]
For example, say we have this method:

```
class Box {
  int getId();
}
```

And we have a call to the method:

```
class Foo
  void doStuff() {
    int len = box.getLength();
  }
}
```

Then later, the return type of `getId` changes to a String (which doesn't affect the method's signature, per https://stackoverflow.com/questions/16149285/does-a-methods-signature-in-java-include-its-return-type ):

```
class Box {
  String getId();
}
```

We need to make sure that the code expecting an `int` will fail static linkage checking.

cc @elharo @suztomo

**Comment by elharo** [comment]
The key question: what, if anything, in the byte code of Foo.class indicates the return type it expects from `getId()`? Is it just a runtime failure when the assignment happens or something more? 

Also note, if `Foo` doesn't use the return value, then the return type change is not a breaking change. For example Foo might do this:

```
box.getId();
```

or this:

```
List list = new ArrayList();
list.put(box.getId());
```

or this:

```
String s = String.valueOf(box.getId());
```

Hmm, that last one might actually break unless the code is recompiled because the wrong valueOf method is invoked, but you can see this is tricky. 

If the return type changes from int to double instead of String, there are more cases where this might not be a breaking change.

**Comment by elharo** [comment]
The return type should be in the byte code as a *[method descriptor](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.3.3)*


A method descriptor looks like (IDLjava/lang/Thread;)Ljava/lang/Object; where the java/lang/Object is the return type. Before that are the parameter types. V means void.

This should be in the constant pool.

**Comment by suztomo** [comment]
I found these descriptors including return type througn BCEL. The method descriptors are available in the MethodSignature class of Friday’s commit.

**Comment by garrettjonesgoogle** [comment]
It may be challenging to figure out the acceptable return types for calling code - it may require inspecting the byte code. For this reason it might be much more complex and expensive to check as compared to our other checks. 

After we understand better how to check this, we could consider implementing it incrementally, if some aspects of it are easier than others.

**Comment by suztomo** [comment]
When method return type changes, it causes NoSuchMethodError, because [JVM's Method Resolution](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-5.html#jvms-5.4.3.3) looks for a method matching name and descriptor (which includes return type). The step doesn't take type hierarchy or byte code into account.


```
# My test to change return type from int to char, causes NoSuchMethodError.
suztomo@suxtomo24:~/signaturechange$ javap -cp target/signature-change-1.0-SNAPSHOT.jar com/google/suztomo/Box
Compiled from "Box.java"
public class com.google.suztomo.Box {
  public com.google.suztomo.Box();
  public char getId();
}
suztomo@suxtomo24:~/signaturechange$ java -cp "target/signature-change-1.0-SNAPSHOT.jar:main-expecting-int.jar" com.google.suztomo.Foo
Exception in thread "main" java.lang.NoSuchMethodError: com.google.suztomo.Box.getId()I
	at com.google.suztomo.Foo.main(Foo.java:7)
```


Rather, finding a example case which is robust to signature (return/argument types) change, i.e. not causing NoSuchMethodError, is difficult.


# Original Proposal

> We need to make sure that the code expecting an int will fail static linkage checking.

Yes, such code fails with `StaticLinkageError` with `SYMBOL_NOT_FOUND` with current StaticLinkageChecker implementation.
