### ISSUE TITLE
BOM release instruction: how to find the oldVersion value?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1804]
The BOM release instruction says:

```
    *  `/google/src/head/depot/google3/devtools/scripts/replace_string "&lt;version>oldVersion&lt;/version>" "&lt;version>newVersion&lt;/version>"`
```

@elharo To create cl/342111902, I checked cl/elharo to find your last change for these documents. For the next release, you may have to check cl/suztomo and cl/elharo to find the last value of `oldValue`. Is there a getter way to find the value of `oldVersion`?

**Comment by elharo** [comment]
Yes, you should be able to just use whatever the old version was. In this case, 15.0.0. We do need to get this all into one cl though since we keep getting blocked by late code reviews. I thought they were all finally up to date, but now I see one cl was still outstanding, with the files you see in cl/342111902

**Comment by suztomo** [comment]
Thanks. Yes, cl/342111902 has been submitted. Now the docs have the latest value. Let's see how it goes.
