### ISSUE TITLE
JLBP-3's special case: not bumping major version upon minimum Java version change

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#371]
@garrettjonesgoogle What do you think about below. (Elliotte and I talked about this Friday. We would like to hear your opinion)

JLBP-3 says

> Special case: Merely bumping up the minimum required Java version (and not making any breaking surface changes) does not necessarily mean that a library should bump its major version, because new Java versions break very little surface from prior versions.
https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/5bed105c7c642bf7efd3b354d4a11bc63b0a5df4/library-best-practices/JLBP-3.md

I think, however, "changing minimum required Java version" matches "when you make incompatible API changes" best, among the three cases explained in Semantic Versioning:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 1. MAJOR version when you make incompatible API changes,
> 2. MINOR version when you add functionality in a backwards-compatible manner, and
> 3. PATCH version when you make backwards-compatible bug fixes.
https://semver.org/

For example, when a library changes minimum required Java version from Java 8 to Java 11, then other Java8 projects that use the library need to update their build configuration to Java 11; otherwise their Java runtime becomes _incompatible_ with the library.

Therefore, I propose that JLBP-3 have "Special case: When bumping up the minimum required Java version, the library should bump its major version, because users of the library need to update their build configuration to use compatible Java version." This is in line with [JLBP-9's second paragraph](https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/library-best-practices/JLBP-9.md) 

Note that [JEP 238: multi-release JAR](https://openjdk.java.net/jeps/238) allows libraries to leverage new Java 11 functionalities without bumping up minimum required Java version to Java 8 or earlier. Thus, multi-release JAR is out of the scope of this discussion.

**Comment by garrettjonesgoogle** [comment]
The special case was meant to be a nod to practicality. Bumping to a new major version can be a lot of effort for some packages, so I tried to carve out the Java upgrade case, because when almost all users are off the old version, then for practical purposes, almost no one is broken (even if technically it's a breaking change). I believe it's a net positive to avoid the major version bump in that case. 

Now for Java 11: isn't it possible to make a Java 8 project be Java 11 compatible? Since Java 11 adoption isn't high yet, why would anyone make Java 11 the minimum version? That should probably wait a while anyway. I certainly agree that requiring Java 11 as a minimum version should be classified as a breaking change because there is so much usage of Java 8 still. 

I do see that the special case in JLBP-3 doesn't explain much of this, so maybe we should expand it some, and probably link it to JLBP-9.

At a higher level, I basically don't think we should be slavish to semantic versioning in 100.00% of cases.

**Comment by suztomo** [comment]
Thank you for clarification. That makes sense. Maybe I can update it with:

"Merely dropping a support of an end-of-life Java version that is not widely used any more  (and not making any breaking surface changes) "

**Comment by garrettjonesgoogle** [comment]
"dropping a support" -> "dropping the support of"
and
"not widely used any more" -> "not widely used by the consumers of a library" **

** Theoretically there could be a very foundational library that happens to be used by a lot of the remaining users of the end-of-life Java version, and they might decide to keep supporting it. I would consider this an optional thing to say, though.
