### ISSUE TITLE
Contribute patch to Beam to use libraries-bom

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#646]

**Comment by elharo** [comment]
https://beam.apache.org/contribute/dependencies/

**Comment by suztomo** [comment]
# Learning Apache Bream
Finished https://cloud.google.com/dataflow/docs/quickstarts . It worked.

![image](https://user-images.githubusercontent.com/28604/68416464-89e30200-0162-11ea-8c33-1c3c5b6353be.png)

IntelliJ shows outdated dependencies:

![image](https://user-images.githubusercontent.com/28604/68416611-cf073400-0162-11ea-8a2b-cfaad9d868da.png)

**Comment by suztomo** [comment]
# beam-sdks-java-io-google-cloud-platform:2.16.0

[`org.apache.beam:beam-sdks-java-io-google-cloud-platform:2.16.0`](https://search.maven.org/artifact/org.apache.beam/beam-sdks-java-io-google-cloud-platform/2.16.0/jar) is the artifact Beam users add for using Beam with Cloud Dataflow. By looking at its dependency tree ([gist](https://gist.github.com/suztomo/db4223a7e6d221f0df1d6c64f4e4fdd1)), the following artifacts are not part of Google Libraries BOM:

- org.apache.beam:beam-sdks-java-core:jar:2.16.0
- org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core:jar:2.16.0
- org.apache.beam:beam-sdks-java-extensions-protobuf:jar:2.16.0
- org.apache.avro:avro:jar:1.8.2
- com.google.cloud.bigdataoss:util:jar:1.9.16
- com.google.auth:google-auth-library-credentials:jar:0.12.0
- com.google.auth:google-auth-library-oauth2-http:jar:0.12.0
- com.google.cloud:google-cloud-bigquerystorage:jar:0.79.0-alpha
- com.google.cloud.bigtable:bigtable-client-core:jar:1.8.0
  This has io.opencensus:opencensus-api:jar:0.15.0
- com.google.cloud.datastore:datastore-v1-proto-client:jar:1.6.0
- io.grpc:grpc-all:jar:1.17.1 (Do we need this?)
- com.fasterxml.jackson.core:jackson-databind:jar:2.9.10
- joda-time:joda-time:jar:2.10.3
- io.netty:netty-handler:jar:4.1.30.Final
- io.netty:netty-tcnative-boringssl-static:jar:2.0.17.Final
- org.slf4j:slf4j-api:jar:1.7.25

**Comment by elharo** [comment]
I doubt we need to add those to the BOM. We simply want to use the BM to set versions for the libraries it does cover. 

We might want to contribute other fixes here. For instance, Beam probably doesn't want grpc-all.

**Comment by suztomo** [comment]
I agree that all of them are too much for our BOM, and non-BOM contribution will be needed.

Memo

# beam/sdks/java/io/google-cloud-platform/build.gradle

beam-sdks-java-io-google-cloud-platform uses Gradle: https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/build.gradle#L30

```
...
dependencies {
  compile project(path: ":sdks:java:core", configuration: "shadow")
  compile project(":sdks:java:extensions:google-cloud-platform-core")
  compile project(":sdks:java:extensions:protobuf")
  compile library.java.avro
  compile library.java.bigdataoss_util
  compile library.java.gax_grpc
  compile library.java.google_api_client
  compile library.java.google_api_services_bigquery
  compile library.java.google_api_services_pubsub
  ...
```

## The source of these variables

Beam uses its own Gradle plugin to set versions

https://github.com/apache/beam/blob/master/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy#L374 (This file is not specific to google-cloud-platform)

```
...
    def google_clients_version = "1.28.0"
    def google_cloud_bigdataoss_version = "1.9.16"
    def google_cloud_core_version = "1.61.0"
    def google_cloud_spanner_version = "1.6.0"
    def grpc_version = "1.17.1"
    def guava_version = "20.0"
    def hadoop_version = "2.7.3"
    def hamcrest_version = "2.1"
...
        google_cloud_datastore_v1_proto_client      : "com.google.cloud.datastore:datastore-v1-proto-client:1.6.0",
        google_cloud_spanner                        : "com.google.cloud:google-cloud-spanner:$google_cloud_spanner_version",
        google_http_client                          : "com.google.http-client:google-http-client:$google_clients_version",
        google_http_client_jackson                  : "com.google.http-client:google-http-client-jackson:$google_clients_version",
        google_http_client_jackson2                 : "com.google.http-client:google-http-client-jackson2:$google_clients_version",
        google_http_client_protobuf                 : "com.google.http-client:google-http-client-protobuf:$google_clients_version",
        google_oauth_client                         : "com.google.oauth-client:google-oauth-client:$google_clients_version",
        google_oauth_client_java6                   : "com.google.oauth-client:google-oauth-client-java6:$google_clients_version",
        grpc_all                                    : "io.grpc:grpc-all:$grpc_version",
...
```

**Comment by suztomo** [comment]
> Human readable reports on status of Beam dependencies are generated weekly by an automated Jenkins job and shared with the Beam community through the dev list.
>
> -- <cite>[Beam: Dependencies Guide](https://beam.apache.org/contribute/dependencies/)</cite>

Found one of the report ([link](https://lists.apache.org/thread.html/d44173baac45d385a8b2d3d5fb3a0252eae80f6fe0881870347d4630@%3Cdev.beam.apache.org%3E)), which does not state gRPC version upgrade. Why?

Subscribed the dev@beam.apache.org and user@beam.apache.org.

> Beam components should define dependencies and their versions at the top level. There can be rare exceptions, but they should come with explanations.

This may require to coordinate with other parts than google-cloud-platform to upgrade library versions.

> JIRA tickets will be created per significant outdated dependency based on the report.
> Title (summary) of the issues will be in the format “Beam Dependency Update Request: " where is the dependency artifact name.
> Issues will be created under the component “dependencies”.

https://issues.apache.org/jira/browse/BEAM-8443?jql=project%20%3D%20BEAM%20AND%20component%20%3D%20dependencies

Creating issues automatically does not upgrade dependency :)
![image](https://user-images.githubusercontent.com/28604/68491554-12bc7500-0219-11ea-82f1-16fbe8613acf.png)

**Comment by suztomo** [comment]
After 1070 is done (almost), 

# Propose Beam to libraries-bom
Gradle can use BOM.

# Propose Beam to have Beam's BOM to import libraries-bom

Beam already has BOM
https://search.maven.org/artifact/org.apache.beam/beam-sdks-java-bom/2.19.0/pom

Concern
- Too many items in libraries-bom
  That may unexpectedly affect other dependencies

**Comment by suztomo** [comment]
# Release Cycle Problem

Suppose the plans above are both implemented, and Beam releaseed Beam BOM 2.20.0 that imports GCP Libraries BOM 4.1.0, including `google-cloud-bigquery:1.107.0` and `google-http-client:1.34.2`.

A Google Cloud Dataflow customer consumes the BOM:

```
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.apache.beam</groupId>
      <artifactId>beam-sdks-java-google-cloud-platform-bom</artifactId>
      <version>2.20.0</version>
    </dependency>
  </dependencies>
</dependencyManagement>
```

1 week later, the customer wants to use `google-cloud-bigquery:1.108.0` that has a new functionality they were looking for. They don't want to wait for another 5 weeks. They try overriding google-cloud-bigquery version:

```
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-bigquery</artifactId>
      <version>1.108.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.beam</groupId>
      <artifactId>beam-sdks-java-google-cloud-platform-bom</artifactId>
      <version>2.20.0</version><!-- This transitively imports google-cloud-bigquery:1.107.0 -->
    </dependency>
  </dependencies>
</dependencyManagement>
```

### Case 1: Newer library version works
Thanks to the up-to-date dependencies in Beam, the customer did not have problem using the newer library version.

### Case 2: Newer library version works
The customer encounters problem in `google-cloud-bigquery:1.108.0`, which turned out to be requiring a new class only available in `google-http-client:1.35.0`. They tries overriding google-http-client version:

```
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-bigquery</artifactId>
      <version>1.108.0</version>
    </dependency>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-http-client</artifactId>
      <version>1.35.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.beam</groupId>
      <artifactId>beam-sdks-java-google-cloud-platform-bom</artifactId>
      <version>2.20.0</version><!-- This transitively imports google-cloud-bigquery:1.107.0 and google-http-client:1.34.2-->
    </dependency>
  </dependencies>
</dependencyManagement>
```


#### Case 2-1: google-http-client:1.35.0 works
The attempt (overriding `google-http-client` to 1.35.0) works.

#### Case 2-2: google-http-client:1.35.0 does not work
The customer's overriding `google-http-client` to 1.35.0 does not work because google-http-client requires yet another dependency upgrade.

The customer finds GCP Libraries BOM 4.2.0 has been released this week, and it has `google-cloud-bigquery:1.108.0`, `google-http-client:1.35.0`, and their up-to-date dependencies such as gRPC and protobuf.

Although there's no guarantee that Libraries BOM 4.2.0 works with Beam 2.20.0, the customer tries explicitly specifying `com.google.cloud:libraries-bom:4.2.0` in `<dependencyManagement>` section in their pom.xml.

```
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>libraries-bom</artifactId>
      <version>4.2.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.beam</groupId>
      <artifactId>beam-sdks-java-google-cloud-platform-bom</artifactId>
      <version>2.20.0</version><!-- This imports libraries-bom:4.1.0 -->
    </dependency>
  </dependencies>
</dependencyManagement>
```

Knowing `libraries-bom:4.2.0` includes `google-cloud-bigquery:1.108.0`, the customer could try this first before trying individual artifact upgrade.

##### Case 2-2-1: libraries-bom:4.2.0 works
The attempt (overriding libraries-bom version to 4.2.0) works.

##### Case 2-2-2: libraries-bom:4.2.0 does not work
Overriding libraries-bom version to 4.2.0 introduces new linkage errors that needs fixes in Beam. For example Beam might use a method only available in `google-cloud-bigquery:1.107.0` or `google-http-client:1.34.2`, not their higher versions.

In this case 2-2-2, the customer needs to wait for next Beam release.

**Comment by saturnism** [comment]
Ideally, Beam gets to control the iteration of releases of what works w/ beam.  To use the newer version, they need to:

1. release a new version of `beam-sdks-java-google-cloud-platform-bom` that works w/ the baseline beam version.
1. the new `beam-sdks-java-google-cloud-platform-bom` would include the right library versions that's _tested_.

the `beam-sdks-java-google-cloud-platform-bom` release cycle can be faster than the Beam release itself.

**Comment by elharo** [comment]
done
